---
title: "IGE and Off-campus study"
output:
  html_document:
    df_print: paged
runtime: shiny
---

```{r Data, echo=FALSE}
# The code here prevents messages from popping up in the Shiny app
library(shiny)
suppressWarnings(suppressMessages(library(dplyr)))
suppressWarnings(suppressMessages(library(leaflet)))
suppressWarnings(suppressMessages(library(maps)))
suppressWarnings(suppressMessages(library(sf)))
library(RColorBrewer)

# Note 1: make variable names in format: first word lowercase, other words uppercase
# Example: firstVariable, secondVariable, yetAnotherVariable

# Note 2: This code chunk modifies the data, and maybe does other code


# Change the file location once I figure out what it's supposed to be
dataFile <- read.csv("https://raw.githubusercontent.com/hollerlu/IGE/main/OCS%20Data%203-7.csv")

activePrograms <- read.csv("https://raw.githubusercontent.com/hollerlu/IGE/main/OCS%2024-25%20Active%20Programs.csv", header = TRUE, stringsAsFactors = FALSE)

# Changed column names, but just changed punctuation
colnames(dataFile) <- c("ApplicationCycle", "Ethnicity", "AnticipatedCompletionDate", "ProgramName", "CountryName", "ProgramCity", "ProgramRegion", "ApplicationID", "ProgramYear", "ProgramTerm", "ApplicationStatusAlias", "Gender", "PreferredGender")


# Replaced "Non-resident alien" with "International student"
dataFile$Ethnicity <- ifelse(dataFile$Ethnicity == "Non-resident alien", "International student", dataFile$Ethnicity)

# Replaced "*<B>Grinnell-in-London</B>" with "Grinnell in London"
dataFile$ProgramName <- ifelse(dataFile$ProgramName == "*<B>Grinnell-in-London</B>", "Grinnell in London", dataFile$ProgramName)


#Adjusted region names to match IEE classification

dataFile$ProgramRegion <- ifelse(dataFile$ProgramRegion == "Latin America", "Latin America and Caribbean", dataFile$ProgramRegion)

dataFile$ProgramRegion <- ifelse(dataFile$ProgramRegion == "South America", "Latin America and Caribbean", dataFile$ProgramRegion)

dataFile$ProgramRegion <- ifelse(dataFile$ProgramRegion == "Caribbean", "Latin America and Caribbean", dataFile$ProgramRegion)


dataFile$ProgramRegion <- ifelse(dataFile$ProgramRegion == "Middle East", "MENA", dataFile$ProgramRegion)

dataFile$ProgramRegion <- ifelse(dataFile$ProgramRegion == "Southeast Asia", "Asia", dataFile$ProgramRegion)

dataFile$ProgramRegion <- ifelse(dataFile$ProgramRegion == "South Asia", "Asia", dataFile$ProgramRegion)

dataFile$ProgramRegion <- ifelse(dataFile$ProgramRegion == "East Asia", "Asia", dataFile$ProgramRegion)

dataFile$ProgramRegion <- ifelse(dataFile$ProgramRegion == "Central Asia", "Asia", dataFile$ProgramRegion)


dataFile$ProgramRegion <- ifelse(dataFile$CountryName == "Tunisia", "MENA", dataFile$ProgramRegion)

dataFile$ProgramRegion <- ifelse(dataFile$CountryName == "Cameroon", "Sub-Saharan Africa", dataFile$ProgramRegion)

dataFile$ProgramRegion <- ifelse(dataFile$CountryName == "Kenya", "Sub-Saharan Africa", dataFile$ProgramRegion)



```

```{r Code, echo=FALSE, eval=FALSE}
# Note 1: This code chunk is good for looking at the data. Set eval=TRUE in the header when
# you want this code to run.


# Includes years as well as semesters
unique(dataFile$ApplicationCycle)


# Has blank values, "Non-resident alien" has been replaced
unique(dataFile$Ethnicity)


# Has blank values
unique(dataFile$AnticipatedCompletionDate)


# "X - ", "x - " and "X-" are individual programs (ask about program abbreviations, i.e. IES)
# Fix "*<B>Grinnell-in-London</B>"
unique(dataFile$ProgramName)


# Nothing to say, maybe ask if there are any issues?
unique(dataFile$CountryName)


# Includes "undefined", and U.S. cities include states
unique(dataFile$ProgramCity)


# Some regions overlap
unique(dataFile$ProgramRegion)


# I think these aren't all unique numbers? 1353/1639
unique(dataFile$ApplicationID)


# Just years, nothing to say
unique(dataFile$ProgramYear)


# "Academic Year", "Fall", and "Spring"
unique(dataFile$ProgramTerm)


# "Approved" and "Intend to Participate"
unique(dataFile$ApplicationStatusAlias)


# "M" and "F"
unique(dataFile$Gender)


# Only value is "NA"
unique(dataFile$PreferredGender)


```

```{r App, echo=FALSE}
server <- function(input, output) {
  
  # Reading in the country information
  worldMap <- read_sf("ne_50m_admin_0_countries.shp")
  
  # Create a dataframe of countries and the number of students who have visited them,
  # but only for active programs
  countryCounts <- dataFile %>%
    filter(ProgramName %in% activePrograms$Program.Name) %>%
    group_by(CountryName)
  
  
  # Changing country names to match the names in worldMap:
  countryCounts$CountryName[countryCounts$CountryName == "Czech Republic"] <- "Czechia"
  countryCounts$CountryName[countryCounts$CountryName == "French Polynesia"] <- "Fr. Polynesia"
  countryCounts$CountryName[countryCounts$CountryName == "Turks and Caicos Islands"] <- "Turks and Caicos Is."
  countryCounts$CountryName[countryCounts$CountryName == "U.S. Virgin Islands"] <- "U.S. Virgin Is."
  countryCounts$CountryName[countryCounts$CountryName == "United States"] <- "United States of America"
  
  # Need to change NAME to CountryName so that the geographical data matches the dataset
  colnames(worldMap)[colnames(worldMap) == "NAME"] <- "CountryName"
  
  # Creating the map
  output$map <- renderLeaflet({
    # Allows for the map to be filtered by Program Year
    filteredCounts <- subset(countryCounts, ProgramYear >= input$yearRange[1] & ProgramYear <= input$yearRange[2])
    
    # Gets the counts of trips per country
    filteredCounts <- filteredCounts %>% summarise(TripCount = n(), ProgramNames = list(ProgramName))
    
    # Putting the TripCounts into worldMap. 
    
    worldMap <- merge(worldMap, filteredCounts, by = 'CountryName', all.x = TRUE)
    
    # Set all other countries to 0 trips
    worldMap$TripCount <- replace(worldMap$TripCount, is.na(worldMap$TripCount), 0)
    
    
    # Creating a color palette for the map
    paletteNum <- colorNumeric("Reds", domain = worldMap$TripCount)
    
    # When a country is clicked on, makes a popup box that shows its name,
    # how many visits it's had, and links to its active programs.
    popupText <- lapply(seq(nrow(worldMap)), function(i) {
      unique_programs <- unique(worldMap$ProgramNames[[i]])
      program_links <- paste("<a href='", activePrograms$TD.link[activePrograms$Program.Name %in% unique_programs], "'>", unique_programs, "</a>", collapse = "<br/>")
      paste(
        "Country: ", worldMap$CountryName[i], "<br/>",
        "Visits: ", worldMap$TripCount[i], "<br/>",
        "Programs: ", paste(program_links, collapse = "<br/>"),
        sep = ""
      )
    }) %>%
      lapply(htmltools::HTML)
    
    
    
    # Sets how far you can zoom so you don't go past the borders
    leaflet(options = leafletOptions(minZoom = 2)) %>%
      # Sets the map
      addProviderTiles("CartoDB.Voyager") %>%
      # Sets the starting viewpoint
      setView(lng = 0, lat = 30, zoom = 2) %>%
      # Sets the limits of scrolling
      setMaxBounds(lng1 = -180, lat1 = -90, lng2 = 180, lat2 = 90) %>%
      # Adds the actual chloropleth map for each country based on how many visits
      addPolygons(data = worldMap, fillColor = ~paletteNum(worldMap$TripCount), weight = 1,
                  color = 'black', smoothFactor = .3, fillOpacity = .75,
                  popup = popupText) %>%
      # Adds a legend
      addLegend(pal = paletteNum, values = worldMap$TripCount,
                title = '<small>Number of students<br>who have visited</small>',
                position = 'bottomleft')
  })
  
  
}

# UI
ui <- fluidPage(
  titlePanel("Student Travel Map"),
  fluidRow(
    column(width = 12,
           leafletOutput("map")
    )
  ),
  fluidRow(
    column(width = 12,
           sliderInput("yearRange", "Select Year Range:",
                       min = min(dataFile$ProgramYear), max = max(dataFile$ProgramYear),
                       value = c(min(dataFile$ProgramYear), max(dataFile$ProgramYear)), step = 1)
    )
  )
)

# Note: if you get a scrollbar in the middle of the page, increase the height or width
shinyApp(ui = ui, server = server, options = list(width = 1000, height = 800))

```